# Generated by Django 5.0.1 on 2024-01-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
