# Generated by Django 5.0.1 on 2024-01-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_delete_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(verbose_name='Ishlab chiqarilgan vaqti'),
        ),
    ]
