# Generated by Django 5.0.1 on 2024-01-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_orderitem_total_price_alter_product_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.shopcart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
