# Generated by Django 5.0.1 on 2024-01-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_rename_product_id_shopcart_product_orderitem_card_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='quantity',
        ),
    ]
