# Generated by Django 5.0.1 on 2024-01-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_remove_shopcart_product_remove_shopcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_id',
        ),
    ]
