# Generated by Django 5.0.1 on 2024-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_remove_product_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Miqdor'),
        ),
    ]
