# Generated by Django 5.0.1 on 2024-02-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_rename_owner_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
