# Generated by Django 4.2.7 on 2024-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_alter_orderitem_mount_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=30, null=True),
        ),
    ]
